
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author User
 */
public class C_TransactionHistory extends javax.swing.JFrame {
    private DefaultTableModel model = new DefaultTableModel();
    private String[] column = {"Date", "Time", "Details", "Amount"};
    
    private Customer customer;
    /**
     * Creates new form TransactionHistory
     */
    public C_TransactionHistory(Customer customer) {
        initComponents();
        model.setColumnIdentifiers(column);
        this.customer = customer;
        tfUsernameTH.setText(customer.getId());
        populateTransactionHistoryTable();
    }

    public C_TransactionHistory() {
        
    }
    
    private void populateTransactionHistoryTable() {
        // Specify the path to your menu text file
        List<Object> container = new ArrayList(TextEditor.fileReader(TextEditor.FilePaths.HISTORY)); 
        
        for (Object object: container) {
            Order orderCast = (Order) object;
            
            
            if (orderCast.getCustomerID().equals(customer.getId())){
                String date = orderCast.getOrderDay()+"/"+orderCast.getOrderMonth()+"/"+orderCast.getOrderYear();
                String[] transactionHistory = {date, orderCast.getTime(), orderCast.getVendorID(), String.valueOf(orderCast.getCost())};
                model.addRow(transactionHistory);
            }
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTransactionHistory = new javax.swing.JPanel();
        lblTransactionHistory = new javax.swing.JLabel();
        pnlTransactionHistoryTable = new javax.swing.JPanel();
        scrlpnlTransactionHistoryTable = new javax.swing.JScrollPane();
        TransactionHistory = new javax.swing.JTable();
        tfUsernameTH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTransactionHistory.setBackground(new java.awt.Color(0, 0, 255));

        lblTransactionHistory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTransactionHistory.setForeground(new java.awt.Color(255, 255, 255));
        lblTransactionHistory.setText("Transaction History");

        javax.swing.GroupLayout pnlTransactionHistoryLayout = new javax.swing.GroupLayout(pnlTransactionHistory);
        pnlTransactionHistory.setLayout(pnlTransactionHistoryLayout);
        pnlTransactionHistoryLayout.setHorizontalGroup(
            pnlTransactionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransactionHistoryLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTransactionHistory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTransactionHistoryLayout.setVerticalGroup(
            pnlTransactionHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransactionHistoryLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTransactionHistory)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlTransactionHistoryTable.setBackground(new java.awt.Color(255, 255, 255));

        scrlpnlTransactionHistoryTable.setViewportView(TransactionHistory);

        tfUsernameTH.setEditable(false);

        javax.swing.GroupLayout pnlTransactionHistoryTableLayout = new javax.swing.GroupLayout(pnlTransactionHistoryTable);
        pnlTransactionHistoryTable.setLayout(pnlTransactionHistoryTableLayout);
        pnlTransactionHistoryTableLayout.setHorizontalGroup(
            pnlTransactionHistoryTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransactionHistoryTableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tfUsernameTH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTransactionHistoryTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlpnlTransactionHistoryTable, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTransactionHistoryTableLayout.setVerticalGroup(
            pnlTransactionHistoryTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTransactionHistoryTableLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tfUsernameTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlpnlTransactionHistoryTable, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTransactionHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTransactionHistoryTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTransactionHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTransactionHistoryTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_TransactionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_TransactionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_TransactionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_TransactionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_TransactionHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TransactionHistory;
    private javax.swing.JLabel lblTransactionHistory;
    private javax.swing.JPanel pnlTransactionHistory;
    private javax.swing.JPanel pnlTransactionHistoryTable;
    private javax.swing.JScrollPane scrlpnlTransactionHistoryTable;
    private javax.swing.JTextField tfUsernameTH;
    // End of variables declaration//GEN-END:variables
}
