import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class RunnerFrame extends javax.swing.JFrame {

    private DeliveryRunner runner;
    private DefaultTableModel taskListModel = new DefaultTableModel();
    private DefaultTableModel tasksModel = new DefaultTableModel();
    private String[] taskListColumns = {"Order Placed", "Vendor", "Customer ID", "Food", "Address"};
    private String[] tasksColumns = {"Time Elapsed", "Vendor", "Customer ID", "Food", "Address"};
    private int row = -1; //-1 = absence of a selected row, can be used as conditions
    
    public RunnerFrame() { //Default constructor for testing purposes
        initComponents();
    }
    
    public RunnerFrame(DeliveryRunner runner) { //Runner object read from textfile and passed to runner frame after log in
        initComponents();
        taskListModel.setColumnIdentifiers(taskListColumns);
        tasksModel.setColumnIdentifiers(tasksColumns);
        this.runner = runner;
        runnerHomeTitlelbl.setText("Welcome Runner " + runner.getId()); //Set title
        
        TextEditor reader = new TextEditor();
        List<Object> container = new ArrayList(reader.fileReader(TextEditor.FilePaths.HISTORY));
        for (Object obj : container) {
            DeliveryOrder dOrder = (DeliveryOrder) obj;
            if (dOrder.getStatusRunner().equals("SEARCHING")) {
                String[] rowDataArray = {
                    dOrder.getTime(), //Retrieve time when order was placed
                    dOrder.getVendorName(), //Retrieve vendor's name
                    dOrder.getCustomer(), //Retrieve customer ID
                    dOrder.getFood(), //Retrieve food name
                    dOrder.getAddress() //Retrieve address
                };
                taskListModel.addRow(rowDataArray);
            }
        }
        reader.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        runnerHomeTitlelbl = new javax.swing.JLabel();
        runnerHomeLogOutbtn = new javax.swing.JButton();
        runnerTaskAcceptbtn = new javax.swing.JButton();
        runnerHomeTaskHistbtn = new javax.swing.JButton();
        runnerHomeDeliveredbtn = new javax.swing.JButton();
        runnerHomeFailedbtn = new javax.swing.JButton();
        runnerHomeYeartxt = new javax.swing.JTextField();
        runnerHomeMonthtxt = new javax.swing.JTextField();
        runnerHomeDaylbl = new javax.swing.JLabel();
        runnerHomeMonthlbl = new javax.swing.JLabel();
        runnerHomeYearlbl = new javax.swing.JLabel();
        runnerHomeTotallbl = new javax.swing.JLabel();
        runnerHomeTotaltxt = new javax.swing.JTextField();
        runnerHomeDaytxt = new javax.swing.JTextField();
        runnerHomeTaskpn = new javax.swing.JScrollPane();
        runnerHomeTaskListtbl = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        runnerHomeTaskstbl = new javax.swing.JTable();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delivery Runner Home Page");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Runner Homepage Frame"); // NOI18N

        runnerHomeTitlelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        runnerHomeTitlelbl.setLabelFor(this);
        runnerHomeTitlelbl.setText("WELCOME HOME, DELIVERY RUNNER");
        runnerHomeTitlelbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        runnerHomeTitlelbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        runnerHomeTitlelbl.setName("Runner Homepage Title"); // NOI18N

        runnerHomeLogOutbtn.setText("LOG OUT");
        runnerHomeLogOutbtn.setName("Runner Home Page Log Out Button"); // NOI18N
        runnerHomeLogOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runnerHomeLogOutbtnActionPerformed(evt);
            }
        });

        runnerTaskAcceptbtn.setText("Accept");
        runnerTaskAcceptbtn.setName("Runner Home Page Accept Task Button"); // NOI18N
        runnerTaskAcceptbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                runnerTaskAcceptbtnMouseClicked(evt);
            }
        });
        runnerTaskAcceptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runnerTaskAcceptbtnActionPerformed(evt);
            }
        });

        runnerHomeTaskHistbtn.setText("Task History");
        runnerHomeTaskHistbtn.setName("Runner Home Page Task History Button"); // NOI18N

        runnerHomeDeliveredbtn.setText("Delivered");
        runnerHomeDeliveredbtn.setName("Runner Home Page Delivered Button"); // NOI18N

        runnerHomeFailedbtn.setText("Failed");
        runnerHomeFailedbtn.setName("Runner Home Page Delivery Failed Button"); // NOI18N

        runnerHomeYeartxt.setText("jTextField2");
        runnerHomeYeartxt.setName("Runner Home Page Yearly Revenue Text Field"); // NOI18N

        runnerHomeMonthtxt.setText("jTextField3");
        runnerHomeMonthtxt.setName("Runner Home Page Monthly Revenue Text Field"); // NOI18N

        runnerHomeDaylbl.setText("Day:");
        runnerHomeDaylbl.setName("Runner Home Page Daily Revenue Label"); // NOI18N

        runnerHomeMonthlbl.setText("Month:");
        runnerHomeMonthlbl.setName("Runner Home Page Monthly Revenue Label"); // NOI18N

        runnerHomeYearlbl.setText("Year:");
        runnerHomeYearlbl.setName("Runner Home Page Yearly Revenue Label"); // NOI18N

        runnerHomeTotallbl.setText("Total:");
        runnerHomeTotallbl.setName("Runner Home Page Total Revenue Label"); // NOI18N

        runnerHomeTotaltxt.setText("jTextField4");
        runnerHomeTotaltxt.setName("Runner Home Page Total Revenue Text Field"); // NOI18N

        runnerHomeDaytxt.setText("jTextField1");
        runnerHomeDaytxt.setName("Runner Home Page Daily Revenue Textfield"); // NOI18N
        runnerHomeDaytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runnerHomeDaytxtActionPerformed(evt);
            }
        });

        runnerHomeTaskpn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Task List", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        runnerHomeTaskListtbl.setModel(taskListModel);
        runnerHomeTaskListtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                runnerHomeTaskListtblMouseReleased(evt);
            }
        });
        runnerHomeTaskpn.setViewportView(runnerHomeTaskListtbl);

        runnerHomeTaskstbl.setModel(tasksModel);
        runnerHomeTaskstbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                runnerHomeTaskstblMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(runnerHomeTaskstbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runnerHomeTitlelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(runnerTaskAcceptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(runnerHomeTaskHistbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(runnerHomeDeliveredbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(runnerHomeFailedbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(runnerHomeLogOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(runnerHomeTaskpn, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(runnerHomeDaylbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(runnerHomeMonthlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(runnerHomeTotallbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(runnerHomeYearlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(runnerHomeDaytxt)
                                    .addComponent(runnerHomeMonthtxt)
                                    .addComponent(runnerHomeYeartxt)
                                    .addComponent(runnerHomeTotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(runnerHomeTitlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runnerHomeDaylbl)
                            .addComponent(runnerHomeDaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runnerHomeMonthlbl)
                            .addComponent(runnerHomeMonthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runnerHomeYeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(runnerHomeYearlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runnerHomeTotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(runnerHomeTotallbl)))
                    .addComponent(jScrollPane1)
                    .addComponent(runnerHomeTaskpn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runnerHomeLogOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(runnerHomeTaskHistbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(runnerHomeDeliveredbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(runnerTaskAcceptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(runnerHomeFailedbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runnerHomeLogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runnerHomeLogOutbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runnerHomeLogOutbtnActionPerformed

    private void runnerTaskAcceptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runnerTaskAcceptbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runnerTaskAcceptbtnActionPerformed

    private void runnerHomeDaytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runnerHomeDaytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runnerHomeDaytxtActionPerformed

    private void runnerHomeTaskstblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runnerHomeTaskstblMouseReleased
        
    }//GEN-LAST:event_runnerHomeTaskstblMouseReleased

    private void runnerHomeTaskListtblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runnerHomeTaskListtblMouseReleased
        row = runnerHomeTaskstbl.getSelectedRow();
    }//GEN-LAST:event_runnerHomeTaskListtblMouseReleased

    private void runnerTaskAcceptbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runnerTaskAcceptbtnMouseClicked
        if (row != -1) { //Fill tasks table with accepted deliveries
            String[] valuesForRow = new String[5];
            for (int columnCounter = 0; columnCounter <= 4; columnCounter++) {
                String columnValues = String.valueOf(taskListModel.getValueAt(row, columnCounter));
                valuesForRow[columnCounter] = columnValues;
            }
            tasksModel.addRow(valuesForRow);
        }
    }//GEN-LAST:event_runnerTaskAcceptbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunnerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunnerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel runnerHomeDaylbl;
    private javax.swing.JTextField runnerHomeDaytxt;
    private javax.swing.JButton runnerHomeDeliveredbtn;
    private javax.swing.JButton runnerHomeFailedbtn;
    private javax.swing.JButton runnerHomeLogOutbtn;
    private javax.swing.JLabel runnerHomeMonthlbl;
    private javax.swing.JTextField runnerHomeMonthtxt;
    private javax.swing.JButton runnerHomeTaskHistbtn;
    private javax.swing.JTable runnerHomeTaskListtbl;
    private javax.swing.JScrollPane runnerHomeTaskpn;
    private javax.swing.JTable runnerHomeTaskstbl;
    private javax.swing.JLabel runnerHomeTitlelbl;
    private javax.swing.JLabel runnerHomeTotallbl;
    private javax.swing.JTextField runnerHomeTotaltxt;
    private javax.swing.JLabel runnerHomeYearlbl;
    private javax.swing.JTextField runnerHomeYeartxt;
    private javax.swing.JButton runnerTaskAcceptbtn;
    // End of variables declaration//GEN-END:variables
}
